/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.TrangChu;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author VITHANH
 */
public class TrangChuContent extends javax.swing.JPanel {

    /**
     * Creates new form TrangChuContent
     */
    public TrangChuContent() {
        initComponents();
        loadBanner();
    }
    private void loadBanner() {
        try {
            ImageIcon originalIcon = new ImageIcon("src/main/java/images/banner.jpg");
            Image img = originalIcon.getImage();

            int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
            int scaledHeight = (screenWidth * originalIcon.getIconHeight()) / originalIcon.getIconWidth();

            Image resized = img.getScaledInstance(screenWidth, scaledHeight, Image.SCALE_SMOOTH);
            banner.setIcon(new ImageIcon(resized));
        } catch (Exception ex) {
            banner.setText("Không thể load ảnh banner.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    // End of variables declaration//GEN-END:variables
}
