/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLPRODUCT;

import com.mycompany.service.Admin.ProductService;
import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Product;
import com.mycompany.model.Category;
import com.mycompany.view.Admin.QLCATEGORY.EditCategory;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;

/**
 *
 * @author VITHANH
 */
public class QuanLyProduct extends javax.swing.JFrame {
    ProductService productService;
    DefaultTableModel defaultTableModel;
    CategoryService categoryService;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyProduct.class.getName());

    /**
     * Creates new form QuanLyProduct
     */
    public QuanLyProduct() {
        initComponents();
        setLocationRelativeTo(null);
        productService = new ProductService();
        categoryService = new CategoryService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Cột ảnh là ImageIcon
                if (columnIndex == 5) return ImageIcon.class;
                return super.getColumnClass(columnIndex);
            }
        };

        // Thêm các cột
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("CATEGORY NAME");
        defaultTableModel.addColumn("NAME");
        defaultTableModel.addColumn("DESCRIPTION");
        defaultTableModel.addColumn("PRICE");
        defaultTableModel.addColumn("IMAGE"); // ✅ Cột ảnh

        Admin_QLPRODUCT_TABLE.setModel(defaultTableModel);
        Admin_QLPRODUCT_TABLE.setRowHeight(60); // ✅ Chiều cao dòng đủ để hiển thị ảnh

        insertData(productService.getAllProduct());

        Admin_QLPRODUCT_TABLE.setComponentPopupMenu(Admin_QLPRODUCT_popupmenu);
    }

    public void insertData(List<Product> productList) {
        defaultTableModel.setRowCount(0); // Xóa dữ liệu cũ

        for (Product pro : productList) {
            Category cate = categoryService.getCategoryByID(pro.getCateid());
            String cateName = (cate != null) ? cate.getName() : "N/A";

            // Xử lý ảnh
            String imagePath = pro.getImagepath(); // Ví dụ: "images/sp1.jpg"
            ImageIcon icon = null;
            File imageFile = new File(imagePath);

            if (imageFile.exists()) {
                Image image = new ImageIcon(imageFile.getAbsolutePath())
                    .getImage()
                    .getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                icon = new ImageIcon(image);
            }

            defaultTableModel.addRow(new Object[]{
                pro.getId(),
                cateName,
                pro.getName(),
                pro.getDescription(),
                pro.getPrice(),
                icon // ✅ Thêm icon vào dòng
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_QLPRODUCT_popupmenu = new javax.swing.JPopupMenu();
        Admin_QLPRODUCT_Edit = new javax.swing.JMenuItem();
        Admin_QLPRODUCT_Remove = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_QLPRODUCT_TABLE = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Admin_QLPRODUCT_Header_Label = new javax.swing.JLabel();
        Admin_QLPRODUCT_Refresh_ProductBTN = new javax.swing.JButton();
        Admin_QLPRODUCT_Add_ProductBTN = new javax.swing.JButton();

        Admin_QLPRODUCT_Edit.setText("Chỉnh sửa");
        Admin_QLPRODUCT_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLPRODUCT_EditActionPerformed(evt);
            }
        });
        Admin_QLPRODUCT_popupmenu.add(Admin_QLPRODUCT_Edit);

        Admin_QLPRODUCT_Remove.setText("Xóa");
        Admin_QLPRODUCT_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLPRODUCT_RemoveActionPerformed(evt);
            }
        });
        Admin_QLPRODUCT_popupmenu.add(Admin_QLPRODUCT_Remove);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Admin_QLPRODUCT_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Admin_QLPRODUCT_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Admin_QLPRODUCT_TABLE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        Admin_QLPRODUCT_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_QLPRODUCT_Header_Label.setText("Quản Lý Product");

        Admin_QLPRODUCT_Refresh_ProductBTN.setText("Refresh");
        Admin_QLPRODUCT_Refresh_ProductBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLPRODUCT_Refresh_ProductBTNActionPerformed(evt);
            }
        });

        Admin_QLPRODUCT_Add_ProductBTN.setText("Thêm");
        Admin_QLPRODUCT_Add_ProductBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLPRODUCT_Add_ProductBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_QLPRODUCT_Add_ProductBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(Admin_QLPRODUCT_Header_Label)
                .addGap(174, 174, 174)
                .addComponent(Admin_QLPRODUCT_Refresh_ProductBTN)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_QLPRODUCT_Refresh_ProductBTN)
                    .addComponent(Admin_QLPRODUCT_Header_Label)
                    .addComponent(Admin_QLPRODUCT_Add_ProductBTN))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_QLPRODUCT_Add_ProductBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLPRODUCT_Add_ProductBTNActionPerformed
        // TODO add your handling code here:
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_Admin_QLPRODUCT_Add_ProductBTNActionPerformed

    private void Admin_QLPRODUCT_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLPRODUCT_EditActionPerformed
        // TODO add your handling code here:
        int row = Admin_QLPRODUCT_TABLE.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn product để sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int id = (int) Admin_QLPRODUCT_TABLE.getValueAt(row, 0);
            new EditProduct(id).setVisible(true);
        } 
    }//GEN-LAST:event_Admin_QLPRODUCT_EditActionPerformed

    private void Admin_QLPRODUCT_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLPRODUCT_RemoveActionPerformed
        // TODO add your handling code here:
        int row = Admin_QLPRODUCT_TABLE.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn product để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int comfirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không ?", "Xóa Product", JOptionPane.YES_NO_OPTION);
            if(comfirm==JOptionPane.YES_OPTION){
                int id = (int) Admin_QLPRODUCT_TABLE.getValueAt(row, 0);
                productService.deleteProductByID(id);
                defaultTableModel.removeRow(row);
            } 
        }
    }//GEN-LAST:event_Admin_QLPRODUCT_RemoveActionPerformed

    private void Admin_QLPRODUCT_Refresh_ProductBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLPRODUCT_Refresh_ProductBTNActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        insertData(productService.getAllProduct());
    }//GEN-LAST:event_Admin_QLPRODUCT_Refresh_ProductBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_QLPRODUCT_Add_ProductBTN;
    private javax.swing.JMenuItem Admin_QLPRODUCT_Edit;
    private javax.swing.JLabel Admin_QLPRODUCT_Header_Label;
    private javax.swing.JButton Admin_QLPRODUCT_Refresh_ProductBTN;
    private javax.swing.JMenuItem Admin_QLPRODUCT_Remove;
    private javax.swing.JTable Admin_QLPRODUCT_TABLE;
    private javax.swing.JPopupMenu Admin_QLPRODUCT_popupmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
