/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLCATEGORY;

import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Category;

/**
 *
 * @author VITHANH
 */
public class EditCategory extends javax.swing.JFrame {
    private int SaveID;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditCategory.class.getName());

    /**
     * Creates new form EditCategory
     */
    public EditCategory(int id){
        initComponents();
        this.SaveID = id;
        CategoryService cateSer = new CategoryService();
        Category cate = cateSer.getCategoryByID(id);
        Admin_Edit_Category_ID.setText(Integer.toString(cate.getId()));
        Admin_Edit_Category_Name.setText(cate.getName());
    }
    public EditCategory() {
//        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Admin_Edit_Category_Header_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Admin_Edit_Category_Name_Label = new javax.swing.JLabel();
        Admin_Edit_Category_ID = new javax.swing.JTextField();
        Admin_Edit_Category_Name = new javax.swing.JTextField();
        Admin_Edit_Category_ID_Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Admin_Edit_Category_SaveBTN = new javax.swing.JButton();
        Admin_Edit_Category_HuyBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Admin_Edit_Category_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_Edit_Category_Header_Label.setText("Sửa Category");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Category_Header_Label)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Admin_Edit_Category_Header_Label)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        Admin_Edit_Category_Name_Label.setText("Name:");

        Admin_Edit_Category_ID.setEditable(false);

        Admin_Edit_Category_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Category_NameActionPerformed(evt);
            }
        });

        Admin_Edit_Category_ID_Label.setText("ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Category_Name_Label)
                        .addGap(51, 51, 51)
                        .addComponent(Admin_Edit_Category_Name))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Category_ID_Label)
                        .addGap(72, 72, 72)
                        .addComponent(Admin_Edit_Category_ID)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Category_ID_Label)
                    .addComponent(Admin_Edit_Category_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Category_Name_Label)
                    .addComponent(Admin_Edit_Category_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Admin_Edit_Category_SaveBTN.setText("Lưu");
        Admin_Edit_Category_SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Category_SaveBTNActionPerformed(evt);
            }
        });

        Admin_Edit_Category_HuyBTN.setText("Hủy");
        Admin_Edit_Category_HuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Category_HuyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_Category_SaveBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Category_HuyBTN)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Category_SaveBTN)
                    .addComponent(Admin_Edit_Category_HuyBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Edit_Category_SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Category_SaveBTNActionPerformed
        // TODO add your handling code here:
        String name = Admin_Edit_Category_Name.getText();
        CategoryService cateSer = new CategoryService();
        Category cate = new Category();
        cate.setId(SaveID);
        cate.setName(name);
        cateSer.updateCategory(cate);
        this.dispose();
    }//GEN-LAST:event_Admin_Edit_Category_SaveBTNActionPerformed

    private void Admin_Edit_Category_HuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Category_HuyBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Admin_Edit_Category_HuyBTNActionPerformed

    private void Admin_Edit_Category_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Category_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_Category_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditCategory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Edit_Category_Header_Label;
    private javax.swing.JButton Admin_Edit_Category_HuyBTN;
    private javax.swing.JTextField Admin_Edit_Category_ID;
    private javax.swing.JLabel Admin_Edit_Category_ID_Label;
    private javax.swing.JTextField Admin_Edit_Category_Name;
    private javax.swing.JLabel Admin_Edit_Category_Name_Label;
    private javax.swing.JButton Admin_Edit_Category_SaveBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
