/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLCATEGORY;

import javax.swing.table.DefaultTableModel;
import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Category;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author VITHANH
 */
public class QuanLyCategory extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyCategory.class.getName());
    DefaultTableModel defaulTableModelQLCATEGORY;
    CategoryService categoryService;
    /**
     * Creates new form QuanLyCategory
     */
    public void insertData(List<Category> cates){
        for(Category cate : cates){
            defaulTableModelQLCATEGORY.addRow(new Object[]{cate.getId(), cate.getName()});
        }
    }
    public QuanLyCategory() {
        initComponents();
        setLocationRelativeTo(null);
        categoryService = new CategoryService();
        
        defaulTableModelQLCATEGORY = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        };
        defaulTableModelQLCATEGORY.addColumn("ID");
        defaulTableModelQLCATEGORY.addColumn("Name");
        
        Admin_QLCATEGORY_TABLE.setModel(defaulTableModelQLCATEGORY);
        
        insertData(categoryService.getAllCategory());
        
        Admin_QLCATEGORY_TABLE.setComponentPopupMenu(QLCategory_popupmenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QLCategory_popupmenu = new javax.swing.JPopupMenu();
        QLCategory_editMenuItem = new javax.swing.JMenuItem();
        QLCategory_deleteMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Admin_QLCATEGORY_Header_Label = new javax.swing.JLabel();
        Admin_QLCATEGORY_Add_CategoryBTN = new javax.swing.JButton();
        Admin_QLCATEGORY_Refresh_CategoryBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_QLCATEGORY_TABLE = new javax.swing.JTable();

        QLCategory_editMenuItem.setText("Sửa");
        QLCategory_editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLCategory_editMenuItemActionPerformed(evt);
            }
        });
        QLCategory_popupmenu.add(QLCategory_editMenuItem);

        QLCategory_deleteMenuItem.setText("Xóa");
        QLCategory_deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLCategory_deleteMenuItemActionPerformed(evt);
            }
        });
        QLCategory_popupmenu.add(QLCategory_deleteMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin_QLCATEGORY_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_QLCATEGORY_Header_Label.setText("Quản Lý Category");

        Admin_QLCATEGORY_Add_CategoryBTN.setText("Thêm");
        Admin_QLCATEGORY_Add_CategoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLCATEGORY_Add_CategoryBTNActionPerformed(evt);
            }
        });

        Admin_QLCATEGORY_Refresh_CategoryBTN.setText("Refresh");
        Admin_QLCATEGORY_Refresh_CategoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLCATEGORY_Refresh_CategoryBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_QLCATEGORY_Add_CategoryBTN)
                .addGap(271, 271, 271)
                .addComponent(Admin_QLCATEGORY_Header_Label)
                .addGap(280, 280, 280)
                .addComponent(Admin_QLCATEGORY_Refresh_CategoryBTN)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_QLCATEGORY_Header_Label)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_QLCATEGORY_Add_CategoryBTN)
                    .addComponent(Admin_QLCATEGORY_Refresh_CategoryBTN))
                .addContainerGap())
        );

        Admin_QLCATEGORY_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Admin_QLCATEGORY_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Admin_QLCATEGORY_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Admin_QLCATEGORY_TABLE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLCategory_deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLCategory_deleteMenuItemActionPerformed
        // TODO add your handling code here:
        int row = Admin_QLCATEGORY_TABLE.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn category để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int comfirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không ?", "Xóa category", JOptionPane.YES_NO_OPTION);
            if(comfirm==JOptionPane.YES_OPTION){
                int id = (int) Admin_QLCATEGORY_TABLE.getValueAt(row, 0);
                categoryService.deleteCategoryByID(id);
                defaulTableModelQLCATEGORY.removeRow(row);
            }
        }
    }//GEN-LAST:event_QLCategory_deleteMenuItemActionPerformed

    private void Admin_QLCATEGORY_Add_CategoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLCATEGORY_Add_CategoryBTNActionPerformed
        // TODO add your handling code here:
        new AddCategory().setVisible(true);
    }//GEN-LAST:event_Admin_QLCATEGORY_Add_CategoryBTNActionPerformed

    private void Admin_QLCATEGORY_Refresh_CategoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLCATEGORY_Refresh_CategoryBTNActionPerformed
        // TODO add your handling code here:
        defaulTableModelQLCATEGORY.setRowCount(0);
        insertData(categoryService.getAllCategory());
    }//GEN-LAST:event_Admin_QLCATEGORY_Refresh_CategoryBTNActionPerformed

    private void QLCategory_editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLCategory_editMenuItemActionPerformed
        // TODO add your handling code here:
        int row = Admin_QLCATEGORY_TABLE.getSelectedRow();
        
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn category để sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int id = (int) Admin_QLCATEGORY_TABLE.getValueAt(row, 0);
            new EditCategory(id).setVisible(true);
        } 
    }//GEN-LAST:event_QLCategory_editMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyCategory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_QLCATEGORY_Add_CategoryBTN;
    private javax.swing.JLabel Admin_QLCATEGORY_Header_Label;
    private javax.swing.JButton Admin_QLCATEGORY_Refresh_CategoryBTN;
    private javax.swing.JTable Admin_QLCATEGORY_TABLE;
    private javax.swing.JMenuItem QLCategory_deleteMenuItem;
    private javax.swing.JMenuItem QLCategory_editMenuItem;
    private javax.swing.JPopupMenu QLCategory_popupmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
