/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package images;


import com.mycompany.view.Admin.QLPRODUCT.*;
import com.mycompany.model.Category;
import com.mycompany.service.Admin.ProductService;
import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Product;
import com.mycompany.model.Category;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author VITHANH
 */
public class EditProduct extends javax.swing.JFrame {
    private int saveID;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProduct.class.getName());
    private String imagePath = null;

    public EditProduct(int id) {
        initComponents();
        setLocationRelativeTo(null);
        this.saveID = id;

        // Gán sự kiện cho nút "Chọn ảnh"
        Admin_Edit_Product_BrowseImage_Btn.addActionListener(e -> chooseImageFile());

        ProductService proSer = new ProductService();
        Product pro = proSer.getProductById(id);
        if (pro == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }

        Admin_Edit_Product_ID_Textfield.setText(String.valueOf(pro.getId()));
        Admin_Edit_Product_Name_Textfield.setText(pro.getName());
        Admin_Edit_Product_Desc_TextArea.setText(pro.getDescription());
        Admin_Edit_Product_Price_Textfield.setText(String.valueOf(pro.getPrice()));
        Admin_Edit_Product_ImagePath_Textfield.setText(pro.getImagepath());
        setImagePreview(pro.getImagepath());

        CategoryService cateSer = new CategoryService();
        List<Category> categoryList = cateSer.getAllCategory();
        Admin_Edit_Product_Category_Combobox.removeAllItems();
        for (Category c : categoryList) {
            Admin_Edit_Product_Category_Combobox.addItem(c.getName());
        }

        Category cate = cateSer.getCategoryByID(pro.getCateid());
        if (cate != null) {
            Admin_Edit_Product_Category_Combobox.setSelectedItem(cate.getName());
        }
    }

    private void chooseImageFile() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh sản phẩm");
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String imageName = selectedFile.getName();
            Path destPath = Paths.get("src/main/java/images", imageName);

            try {
                Files.copy(selectedFile.toPath(), destPath, StandardCopyOption.REPLACE_EXISTING);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi sao chép ảnh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String relativePath = "images/" + imageName;
            Admin_Edit_Product_ImagePath_Textfield.setText(relativePath);
            setImagePreview(relativePath);
        }
    }

    private void setImagePreview(String imagePath) {
        try {
            // Lấy đường dẫn tuyệt đối tới ảnh dựa trên thư mục làm việc hiện tại
            Path currentDir = Paths.get("").toAbsolutePath(); // thư mục gốc của project khi chạy
            File file = currentDir.resolve(imagePath).toFile(); // nối imagePath (VD: images/xxx.jpg)

            if (!file.exists()) {
                System.out.println("Ảnh không tồn tại: " + file.getAbsolutePath());
                Admin_EditProduct_ImagePreview.setIcon(null);
                return;
            }

            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(
                Admin_EditProduct_ImagePreview.getWidth(),
                Admin_EditProduct_ImagePreview.getHeight(),
                Image.SCALE_SMOOTH
            );
            Admin_EditProduct_ImagePreview.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Admin_Edit_Product_Header_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Admin_Edit_Product_Name_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ImagePath_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ID_Label = new javax.swing.JLabel();
        Admin_Edit_Product_Category_Label = new javax.swing.JLabel();
        Admin_Edit_Product_Name_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_Price_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ID_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_ImagePath_Textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_Edit_Product_Desc_TextArea = new javax.swing.JTextArea();
        Admin_Edit_Product_Price_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_Category_Combobox = new javax.swing.JComboBox<>();
        Admin_Edit_Product_Description_Label = new javax.swing.JLabel();
        Admin_EditProduct_ImagePreview = new javax.swing.JLabel();
        Admin_Edit_Product_BrowseImage_Btn = new javax.swing.JButton();
        lblAnh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Admin_Edit_Product_HuyBTN = new javax.swing.JButton();
        Admin_Edit_Product_SaveBTN = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Admin_Edit_Product_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_Edit_Product_Header_Label.setText("Chỉnh sửa Product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Product_Header_Label)
                .addGap(296, 296, 296))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_Product_Header_Label)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Admin_Edit_Product_Name_Label.setText("Name: ");

        Admin_Edit_Product_ImagePath_Label.setText("Imagepath:");

        Admin_Edit_Product_ID_Label.setText("ID:");

        Admin_Edit_Product_Category_Label.setText("Category: ");

        Admin_Edit_Product_Price_Label.setText("Price: ");

        Admin_Edit_Product_ID_Textfield.setEditable(false);

        Admin_Edit_Product_Desc_TextArea.setColumns(20);
        Admin_Edit_Product_Desc_TextArea.setRows(5);
        jScrollPane1.setViewportView(Admin_Edit_Product_Desc_TextArea);

        Admin_Edit_Product_Description_Label.setText("Description:");

        Admin_Edit_Product_BrowseImage_Btn.setText("Chọn ảnh");
        Admin_Edit_Product_BrowseImage_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Product_BrowseImage_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Admin_Edit_Product_Name_Label)
                                .addGap(18, 18, 18)
                                .addComponent(Admin_Edit_Product_Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Admin_Edit_Product_ID_Label)
                                .addGap(42, 42, 42)
                                .addComponent(Admin_Edit_Product_ID_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Admin_Edit_Product_Category_Label)
                            .addComponent(Admin_Edit_Product_Price_Label))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Edit_Product_Price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Edit_Product_Category_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Admin_Edit_Product_Description_Label)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Admin_Edit_Product_ImagePath_Label)
                                .addGap(18, 18, 18)
                                .addComponent(Admin_Edit_Product_ImagePath_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Admin_Edit_Product_BrowseImage_Btn)
                                .addGap(48, 48, 48)))
                        .addComponent(Admin_EditProduct_ImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_Product_ID_Label)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Admin_Edit_Product_ID_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Admin_Edit_Product_Category_Label)
                        .addComponent(Admin_Edit_Product_Category_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Product_Name_Label)
                    .addComponent(Admin_Edit_Product_Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Edit_Product_Description_Label)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admin_Edit_Product_ImagePath_Label)
                            .addComponent(Admin_Edit_Product_ImagePath_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Edit_Product_BrowseImage_Btn))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admin_Edit_Product_Price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Edit_Product_Price_Label))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Admin_EditProduct_ImagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))))
        );

        Admin_Edit_Product_HuyBTN.setText("Hủy");
        Admin_Edit_Product_HuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Product_HuyBTNActionPerformed(evt);
            }
        });

        Admin_Edit_Product_SaveBTN.setText("Lưu");
        Admin_Edit_Product_SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Product_SaveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_Product_SaveBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Product_HuyBTN)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Product_HuyBTN)
                    .addComponent(Admin_Edit_Product_SaveBTN))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Edit_Product_HuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Product_HuyBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Admin_Edit_Product_HuyBTNActionPerformed

    private void Admin_Edit_Product_SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Product_SaveBTNActionPerformed
        // TODO add your handling code here:
        String name = Admin_Edit_Product_Name_Textfield.getText();
    String description = Admin_Edit_Product_Desc_TextArea.getText();
    String priceText = Admin_Edit_Product_Price_Textfield.getText();
    String imagePath = Admin_Edit_Product_ImagePath_Textfield.getText();
    String categoryName = (String) Admin_Edit_Product_Category_Combobox.getSelectedItem();

    // Ép kiểu và kiểm tra dữ liệu đầu vào (bạn có thể bổ sung validate nếu muốn)
    double price = 0.0;
    try {
        price = Double.parseDouble(priceText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Giá không hợp lệ!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lấy ID Category từ tên Category
    CategoryService cateSer = new CategoryService();
    Category category = cateSer.getCategoryByName(categoryName); // 🔸 Giả sử bạn có hàm này
    if (category == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy danh mục!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tạo đối tượng Product
    Product product = new Product();
    product.setId(saveID); // saveID là ID của product đang sửa
    product.setName(name);
    product.setDescription(description);
    product.setPrice(price);
    product.setImagepath(imagePath);
    product.setCateid(category.getId());

    // Cập nhật DB
    ProductService proSer = new ProductService();
    proSer.updateProduct(product);

    // Đóng form sau khi lưu xong
    this.dispose();
    }//GEN-LAST:event_Admin_Edit_Product_SaveBTNActionPerformed

    private void Admin_Edit_Product_BrowseImage_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Product_BrowseImage_BtnActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Chọn ảnh sản phẩm");
    fileChooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "jpeg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        String fileName = selectedFile.getName();
        File destDir = new File("images");
        if (!destDir.exists()) {
            destDir.mkdirs();
        }

        File destFile = new File(destDir, fileName);

        try {
            Files.copy(selectedFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            imagePath = "images/" + fileName;

            // Hiển thị ảnh lên JLabel
            ImageIcon icon = new ImageIcon(imagePath);
            Image scaledImage = icon.getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
            lblAnh.setIcon(new ImageIcon(scaledImage));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi copy ảnh: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_Admin_Edit_Product_BrowseImage_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    String input = JOptionPane.showInputDialog("Nhập ID sản phẩm để sửa:");
        try {
            int id = Integer.parseInt(input);
            new EditProduct(id).setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_EditProduct_ImagePreview;
    private javax.swing.JButton Admin_Edit_Product_BrowseImage_Btn;
    private javax.swing.JComboBox<String> Admin_Edit_Product_Category_Combobox;
    private javax.swing.JLabel Admin_Edit_Product_Category_Label;
    private javax.swing.JTextArea Admin_Edit_Product_Desc_TextArea;
    private javax.swing.JLabel Admin_Edit_Product_Description_Label;
    private javax.swing.JLabel Admin_Edit_Product_Header_Label;
    private javax.swing.JButton Admin_Edit_Product_HuyBTN;
    private javax.swing.JLabel Admin_Edit_Product_ID_Label;
    private javax.swing.JTextField Admin_Edit_Product_ID_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_ImagePath_Label;
    private javax.swing.JTextField Admin_Edit_Product_ImagePath_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_Name_Label;
    private javax.swing.JTextField Admin_Edit_Product_Name_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_Price_Label;
    private javax.swing.JTextField Admin_Edit_Product_Price_Textfield;
    private javax.swing.JButton Admin_Edit_Product_SaveBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblAnh;
    // End of variables declaration//GEN-END:variables
}
