/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLUSER;

import com.mycompany.service.Admin.UserService;
import com.mycompany.model.User;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author VITHANH
 */
public class AddUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddUser.class.getName());

    /**
     * Creates new form AddUser
     */
    
    public AddUser() {
        initComponents();
        setLocationRelativeTo(null);
    }

//    public User getUser(){
//        
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Amin_Add_User_Role_ButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Admin_Add_User_SaveBTN = new javax.swing.JButton();
        Admin_Add_User_HuyBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Admin_Add_User_Header_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Admin_Add_User_Username_Label = new javax.swing.JLabel();
        Admin_Add_User_Username_TextField = new javax.swing.JTextField();
        Admin_Add_User_Password_Label = new javax.swing.JLabel();
        Admin_Add_User_Password_TextField = new javax.swing.JPasswordField();
        Admin_Add_User_Name_Label = new javax.swing.JLabel();
        Admin_Add_User_Name = new javax.swing.JTextField();
        Admin_Add_User_Role_Label = new javax.swing.JLabel();
        Amin_Add_User_Role_Admin_RadioBTN = new javax.swing.JRadioButton();
        Amin_Add_User_Role_Customer_RadioBTN = new javax.swing.JRadioButton();
        Admin_Add_User_Phone_Label = new javax.swing.JLabel();
        Admin_Add_User_Phone = new javax.swing.JTextField();
        Admin_Add_User_About_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_Add_User_About = new javax.swing.JTextArea();
        Admin_Add_User_Email_Label = new javax.swing.JLabel();
        Admin_Add_User_Adress = new javax.swing.JTextField();
        Admin_Add_User_Address_Label = new javax.swing.JLabel();
        Admin_Add_User_Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm User");
        setLocation(new java.awt.Point(0, 0));

        Admin_Add_User_SaveBTN.setText("Lưu");
        Admin_Add_User_SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_SaveBTNActionPerformed(evt);
            }
        });

        Admin_Add_User_HuyBTN.setText("Hủy");
        Admin_Add_User_HuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_HuyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Admin_Add_User_SaveBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Add_User_HuyBTN)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Add_User_SaveBTN)
                    .addComponent(Admin_Add_User_HuyBTN)))
        );

        Admin_Add_User_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_Add_User_Header_Label.setText("Thêm user");

        Admin_Add_User_Username_Label.setText("Username:");

        Admin_Add_User_Username_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_Username_TextFieldActionPerformed(evt);
            }
        });

        Admin_Add_User_Password_Label.setText("Password:");

        Admin_Add_User_Password_TextField.setText("123456789");

        Admin_Add_User_Name_Label.setText("Name:");

        Admin_Add_User_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_NameActionPerformed(evt);
            }
        });

        Admin_Add_User_Role_Label.setText("Role:");

        Amin_Add_User_Role_ButtonGroup.add(Amin_Add_User_Role_Admin_RadioBTN);
        Amin_Add_User_Role_Admin_RadioBTN.setText("Admin");
        Amin_Add_User_Role_Admin_RadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amin_Add_User_Role_Admin_RadioBTNActionPerformed(evt);
            }
        });

        Amin_Add_User_Role_ButtonGroup.add(Amin_Add_User_Role_Customer_RadioBTN);
        Amin_Add_User_Role_Customer_RadioBTN.setText("Customer");
        Amin_Add_User_Role_Customer_RadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amin_Add_User_Role_Customer_RadioBTNActionPerformed(evt);
            }
        });

        Admin_Add_User_Phone_Label.setText("Phone:");

        Admin_Add_User_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_PhoneActionPerformed(evt);
            }
        });

        Admin_Add_User_About_Label.setText("About:");

        Admin_Add_User_About.setColumns(20);
        Admin_Add_User_About.setRows(5);
        jScrollPane1.setViewportView(Admin_Add_User_About);

        Admin_Add_User_Email_Label.setText("Email:");

        Admin_Add_User_Adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_AdressActionPerformed(evt);
            }
        });

        Admin_Add_User_Address_Label.setText("Address:");

        Admin_Add_User_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Add_User_EmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Add_User_Role_Label)
                            .addComponent(Admin_Add_User_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Add_User_Email_Label)
                            .addComponent(Admin_Add_User_Address_Label)
                            .addComponent(Admin_Add_User_Phone_Label)
                            .addComponent(Admin_Add_User_About_Label))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Add_User_Name)
                            .addComponent(Admin_Add_User_Phone)
                            .addComponent(jScrollPane1)
                            .addComponent(Admin_Add_User_Adress)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Amin_Add_User_Role_Admin_RadioBTN)
                                .addGap(50, 50, 50)
                                .addComponent(Amin_Add_User_Role_Customer_RadioBTN)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Admin_Add_User_Email)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Admin_Add_User_Password_Label)
                            .addComponent(Admin_Add_User_Username_Label))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Add_User_Username_TextField)
                            .addComponent(Admin_Add_User_Password_TextField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Add_User_Username_Label)
                    .addComponent(Admin_Add_User_Username_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Add_User_Password_Label)
                    .addComponent(Admin_Add_User_Password_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Add_User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Add_User_Name_Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Add_User_Role_Label)
                    .addComponent(Amin_Add_User_Role_Admin_RadioBTN)
                    .addComponent(Amin_Add_User_Role_Customer_RadioBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin_Add_User_Email_Label)
                    .addComponent(Admin_Add_User_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin_Add_User_Address_Label)
                    .addComponent(Admin_Add_User_Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin_Add_User_Phone_Label)
                    .addComponent(Admin_Add_User_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Add_User_About_Label))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(Admin_Add_User_Header_Label)
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Add_User_Header_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Add_User_SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_SaveBTNActionPerformed
        // TODO add your handling code here:
            UserService userService = new UserService();
            User user = new User();

            String username = Admin_Add_User_Username_TextField.getText();
            String password = new String(Admin_Add_User_Password_TextField.getPassword());
            String name = Admin_Add_User_Name.getText();
            String email = Admin_Add_User_Email.getText();
            String address = Admin_Add_User_Adress.getText();
            char role = 0;
            if (Amin_Add_User_Role_Admin_RadioBTN.isSelected()) {
                role = 'A';
            } else if (Amin_Add_User_Role_Customer_RadioBTN.isSelected()) {
                role = 'C';
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vai trò (Admin hoặc Customer)");
                return; // thoát không insert
            }

            String phone = Admin_Add_User_Phone.getText();
            String about = Admin_Add_User_About.getText();

            user.setUsername(username);
            user.setPassword(password);
            user.setName(name);
            user.setAddress(address);
            user.setEmail(email);
            user.setRole(role);
            user.setPhone(phone);
            user.setAbout(about);

            userService.insert(user);

            this.dispose();
    }//GEN-LAST:event_Admin_Add_User_SaveBTNActionPerformed

    private void Admin_Add_User_HuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_HuyBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Admin_Add_User_HuyBTNActionPerformed

    private void Admin_Add_User_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Add_User_EmailActionPerformed

    private void Admin_Add_User_AdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_AdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Add_User_AdressActionPerformed

    private void Admin_Add_User_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Add_User_PhoneActionPerformed

    private void Amin_Add_User_Role_Customer_RadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amin_Add_User_Role_Customer_RadioBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amin_Add_User_Role_Customer_RadioBTNActionPerformed

    private void Amin_Add_User_Role_Admin_RadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amin_Add_User_Role_Admin_RadioBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amin_Add_User_Role_Admin_RadioBTNActionPerformed

    private void Admin_Add_User_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Add_User_NameActionPerformed

    private void Admin_Add_User_Username_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Add_User_Username_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Add_User_Username_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Admin_Add_User_About;
    private javax.swing.JLabel Admin_Add_User_About_Label;
    private javax.swing.JLabel Admin_Add_User_Address_Label;
    private javax.swing.JTextField Admin_Add_User_Adress;
    private javax.swing.JTextField Admin_Add_User_Email;
    private javax.swing.JLabel Admin_Add_User_Email_Label;
    private javax.swing.JLabel Admin_Add_User_Header_Label;
    private javax.swing.JButton Admin_Add_User_HuyBTN;
    private javax.swing.JTextField Admin_Add_User_Name;
    private javax.swing.JLabel Admin_Add_User_Name_Label;
    private javax.swing.JLabel Admin_Add_User_Password_Label;
    private javax.swing.JPasswordField Admin_Add_User_Password_TextField;
    private javax.swing.JTextField Admin_Add_User_Phone;
    private javax.swing.JLabel Admin_Add_User_Phone_Label;
    private javax.swing.JLabel Admin_Add_User_Role_Label;
    private javax.swing.JButton Admin_Add_User_SaveBTN;
    private javax.swing.JLabel Admin_Add_User_Username_Label;
    private javax.swing.JTextField Admin_Add_User_Username_TextField;
    private javax.swing.JRadioButton Amin_Add_User_Role_Admin_RadioBTN;
    private javax.swing.ButtonGroup Amin_Add_User_Role_ButtonGroup;
    private javax.swing.JRadioButton Amin_Add_User_Role_Customer_RadioBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
