/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLUSER;

import com.mycompany.service.Admin.UserService;
import com.mycompany.model.User;
import javax.swing.JOptionPane;
/**
 *
 * @author VITHANH
 */
public class EditUser extends javax.swing.JFrame {
    private int saveID;

    public int getSaveID() {
        return saveID;
    }

    public void setSaveID(int saveID) {
        this.saveID = saveID;
    }
    
    public EditUser(int id) {
    this.saveID = id;
    initComponents(); // Khởi tạo giao diện

    UserService userService = new UserService();
    User user = userService.getUserByID(this.saveID);

    if (user != null) {
        // Set dữ liệu lên các TextField
        Admin_Edit_User_Username_TextField.setText(user.getUsername());
        Admin_Edit_User_Password_TextField.setText(user.getPassword());
        Admin_Edit_User_Email.setText(user.getEmail());
        Admin_Edit_User_Address.setText(user.getAddress());
        Admin_Edit_User_Name.setText(user.getName());
        Admin_Edit_User_Phone.setText(String.valueOf(user.getPhone()));
        Admin_Edit_User_About.setText(user.getAbout());

        // Set Radio button theo role
        if (user.getRole() == 'A') {
            Amin_Edit_User_Role_Admin_RadioBTN.setSelected(true);
        } else if (user.getRole() == 'C') {
            Amin_Edit_User_Role_Customer_RadioBTN.setSelected(true);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy người dùng với ID = " + id);
    }
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditUser.class.getName());

    /**
     * Creates new form EditUser
     */
    public EditUser() {
//        initComponents();
//        UserService userService = new UserService();
//        
//        User user = userService.getUserByID(this.saveID); 
//        
//        Admin_Edit_User_Username_TextField.setText(user.getUsername());
//        new String(Admin_Edit_User_Password_TextField.());
//        String name = Admin_Edit_User_Name.getText();
//        char role = 0;
//        if (Amin_Edit_User_Role_Admin_RadioBTN.isSelected()) {
//            role = 'A';
//        } else if (Amin_Edit_User_Role_Customer_RadioBTN.isSelected()) {
//            role = 'C';
//        } else {
//            JOptionPane.showMessageDialog(null, "Vui lòng chọn vai trò (Admin hoặc Customer)");
//            return; // thoát không insert
//        }
//
//        int phone = Integer.parseInt(Admin_Edit_User_Phone.getText());
//        String about = Admin_Edit_User_About_Label.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Edit_User_BTNGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Admin_Edit_User_Username_Label = new javax.swing.JLabel();
        Admin_Edit_User_Username_TextField = new javax.swing.JTextField();
        Admin_Edit_User_Password_Label = new javax.swing.JLabel();
        Admin_Edit_User_Password_TextField = new javax.swing.JPasswordField();
        Admin_Edit_User_Name_Label = new javax.swing.JLabel();
        Admin_Edit_User_Name = new javax.swing.JTextField();
        Admin_Edit_User_Role_Label = new javax.swing.JLabel();
        Amin_Edit_User_Role_Admin_RadioBTN = new javax.swing.JRadioButton();
        Amin_Edit_User_Role_Customer_RadioBTN = new javax.swing.JRadioButton();
        Admin_Edit_User_Phone_Label = new javax.swing.JLabel();
        Admin_Edit_User_Email = new javax.swing.JTextField();
        Admin_Edit_User_About_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_Edit_User_About = new javax.swing.JTextArea();
        Admin_Edit_User_Email_Label = new javax.swing.JLabel();
        Admin_Edit_User_Phone = new javax.swing.JTextField();
        Admin_Edit_User_Email_Label1 = new javax.swing.JLabel();
        Admin_Edit_User_Address = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Admin_Edit_User_SaveBTN = new javax.swing.JButton();
        Admin_Edit_User_HuyBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Admin_Edit_User_Header_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Admin_Edit_User_Username_Label.setText("Username:");

        Admin_Edit_User_Username_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_Username_TextFieldActionPerformed(evt);
            }
        });

        Admin_Edit_User_Password_Label.setText("Password:");

        Admin_Edit_User_Password_TextField.setText("123456789");

        Admin_Edit_User_Name_Label.setText("Name:");

        Admin_Edit_User_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_NameActionPerformed(evt);
            }
        });

        Admin_Edit_User_Role_Label.setText("Role:");

        Admin_Edit_User_BTNGroup.add(Amin_Edit_User_Role_Admin_RadioBTN);
        Amin_Edit_User_Role_Admin_RadioBTN.setText("Admin");
        Amin_Edit_User_Role_Admin_RadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amin_Edit_User_Role_Admin_RadioBTNActionPerformed(evt);
            }
        });

        Admin_Edit_User_BTNGroup.add(Amin_Edit_User_Role_Customer_RadioBTN);
        Amin_Edit_User_Role_Customer_RadioBTN.setText("Customer");
        Amin_Edit_User_Role_Customer_RadioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amin_Edit_User_Role_Customer_RadioBTNActionPerformed(evt);
            }
        });

        Admin_Edit_User_Phone_Label.setText("Phone:");

        Admin_Edit_User_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_EmailActionPerformed(evt);
            }
        });

        Admin_Edit_User_About_Label.setText("About");

        Admin_Edit_User_About.setColumns(20);
        Admin_Edit_User_About.setRows(5);
        jScrollPane1.setViewportView(Admin_Edit_User_About);

        Admin_Edit_User_Email_Label.setText("Email:");

        Admin_Edit_User_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_PhoneActionPerformed(evt);
            }
        });

        Admin_Edit_User_Email_Label1.setText("Address:");

        Admin_Edit_User_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_AddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_About_Label)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_Username_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_Edit_User_Username_TextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_Password_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_Edit_User_Password_TextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_Edit_User_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Edit_User_Role_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Amin_Edit_User_Role_Admin_RadioBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Amin_Edit_User_Role_Customer_RadioBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Admin_Edit_User_Name)
                                .addGap(3, 3, 3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_Email_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_Edit_User_Email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_Phone_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_Edit_User_Phone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_User_Email_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Admin_Edit_User_Address)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_User_Username_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Edit_User_Username_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_User_Password_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Edit_User_Password_Label))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_User_Name_Label)
                    .addComponent(Admin_Edit_User_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_User_Role_Label)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Amin_Edit_User_Role_Admin_RadioBTN)
                        .addComponent(Amin_Edit_User_Role_Customer_RadioBTN)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_User_Email_Label)
                    .addComponent(Admin_Edit_User_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_User_Email_Label1)
                    .addComponent(Admin_Edit_User_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_User_Phone_Label)
                    .addComponent(Admin_Edit_User_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_User_About_Label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        Admin_Edit_User_SaveBTN.setText("Lưu");
        Admin_Edit_User_SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_SaveBTNActionPerformed(evt);
            }
        });

        Admin_Edit_User_HuyBTN.setText("Hủy");
        Admin_Edit_User_HuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_User_HuyBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_User_SaveBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_User_HuyBTN)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_User_SaveBTN)
                    .addComponent(Admin_Edit_User_HuyBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admin_Edit_User_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_Edit_User_Header_Label.setText("Edit User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(Admin_Edit_User_Header_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_User_Header_Label)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Edit_User_Username_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_Username_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_User_Username_TextFieldActionPerformed

    private void Admin_Edit_User_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_User_NameActionPerformed

    private void Amin_Edit_User_Role_Customer_RadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amin_Edit_User_Role_Customer_RadioBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amin_Edit_User_Role_Customer_RadioBTNActionPerformed

    private void Amin_Edit_User_Role_Admin_RadioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amin_Edit_User_Role_Admin_RadioBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amin_Edit_User_Role_Admin_RadioBTNActionPerformed

    private void Admin_Edit_User_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_User_EmailActionPerformed

    private void Admin_Edit_User_SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_SaveBTNActionPerformed
        // TODO add your handling code here:
        
        UserService userService = new UserService();
        User user = new User(saveID);
        
        
        
        
        String username = Admin_Edit_User_Username_TextField.getText();
        String password = new String(Admin_Edit_User_Password_TextField.getPassword());
        String email = Admin_Edit_User_Email.getText();
        String address = Admin_Edit_User_Address.getText();
        String name = Admin_Edit_User_Name.getText();
        char role = 0;
        if (Amin_Edit_User_Role_Admin_RadioBTN.isSelected()) {
            role = 'A';
        } else if (Amin_Edit_User_Role_Customer_RadioBTN.isSelected()) {
            role = 'C';
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn vai trò (Admin hoặc Customer)");
            return; // thoát không insert
        }

        int phone = Integer.parseInt(Admin_Edit_User_Phone.getText());
        String about = Admin_Edit_User_About_Label.getText();

        user.setUsername(username);
        user.setPassword(password);
        user.setEmail(email);
        user.setAddress(address);
        user.setName(name);
        user.setRole(role);
        user.setPhone(phone);
        user.setAbout(about);

        userService.update(user);

        this.dispose();
    }//GEN-LAST:event_Admin_Edit_User_SaveBTNActionPerformed

    private void Admin_Edit_User_HuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_HuyBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Admin_Edit_User_HuyBTNActionPerformed

    private void Admin_Edit_User_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_User_PhoneActionPerformed

    private void Admin_Edit_User_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_User_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_User_AddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Admin_Edit_User_About;
    private javax.swing.JLabel Admin_Edit_User_About_Label;
    private javax.swing.JTextField Admin_Edit_User_Address;
    private javax.swing.ButtonGroup Admin_Edit_User_BTNGroup;
    private javax.swing.JTextField Admin_Edit_User_Email;
    private javax.swing.JLabel Admin_Edit_User_Email_Label;
    private javax.swing.JLabel Admin_Edit_User_Email_Label1;
    private javax.swing.JLabel Admin_Edit_User_Header_Label;
    private javax.swing.JButton Admin_Edit_User_HuyBTN;
    private javax.swing.JTextField Admin_Edit_User_Name;
    private javax.swing.JLabel Admin_Edit_User_Name_Label;
    private javax.swing.JLabel Admin_Edit_User_Password_Label;
    private javax.swing.JPasswordField Admin_Edit_User_Password_TextField;
    private javax.swing.JTextField Admin_Edit_User_Phone;
    private javax.swing.JLabel Admin_Edit_User_Phone_Label;
    private javax.swing.JLabel Admin_Edit_User_Role_Label;
    private javax.swing.JButton Admin_Edit_User_SaveBTN;
    private javax.swing.JLabel Admin_Edit_User_Username_Label;
    private javax.swing.JTextField Admin_Edit_User_Username_TextField;
    private javax.swing.JRadioButton Amin_Edit_User_Role_Admin_RadioBTN;
    private javax.swing.JRadioButton Amin_Edit_User_Role_Customer_RadioBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
