/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view.Admin.QLUSER;

import com.mycompany.service.Admin.UserService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.mycompany.model.User;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
/**
 *
 * @author VITHANH
 */
public class QuanLyUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyUser.class.getName());
    DefaultTableModel defaultTableModelQLUSER;
    UserService userService;
    /**
     * Creates new form QuanLyUser
     */
    private void InsertData(List<User> users){
        for(User user : users){
            defaultTableModelQLUSER.addRow(new Object[]{user.getId(), user.getName(), user.getPhone(), user.getUsername(), user.getPassword(),user.getEmail() ,user.getAddress(), user.getAbout(), user.getRole(), user.getFavorites()});
        }
    }
    public QuanLyUser() {
        initComponents();
        setLocationRelativeTo(null);
        userService = new UserService();
        
        defaultTableModelQLUSER = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        };
        
        Admin_QLUSER_TABLE.setModel(defaultTableModelQLUSER);
        
        defaultTableModelQLUSER.addColumn("ID");
        defaultTableModelQLUSER.addColumn("Name");
        defaultTableModelQLUSER.addColumn("Phone");
        defaultTableModelQLUSER.addColumn("Username");
        defaultTableModelQLUSER.addColumn("Password");
        defaultTableModelQLUSER.addColumn("Email");
        defaultTableModelQLUSER.addColumn("Address");
        defaultTableModelQLUSER.addColumn("About");
        defaultTableModelQLUSER.addColumn("Role");
        defaultTableModelQLUSER.addColumn("Favorites");
        
        InsertData(userService.getAllUser());
        

        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem editItem = new JMenuItem("Sửa");
        JMenuItem deleteItem = new JMenuItem("Xóa");

        popupMenu.add(editItem);
        popupMenu.add(deleteItem);

        // Gắn popup menu cho JTable
        Admin_QLUSER_TABLE.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }

            private void showPopup(MouseEvent e) {
                int row = Admin_QLUSER_TABLE.rowAtPoint(e.getPoint());
                if (row >= 0 && row < Admin_QLUSER_TABLE.getRowCount()) {
                    Admin_QLUSER_TABLE.setRowSelectionInterval(row, row);
                    popupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
        deleteItem.addActionListener(e -> {
        int selectedRow = Admin_QLUSER_TABLE.getSelectedRow();
        if (selectedRow >= 0) {
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa người dùng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int id = (int) defaultTableModelQLUSER.getValueAt(selectedRow, 0);
            userService.deleteById(id); // gọi DAO để xóa DB
            defaultTableModelQLUSER.removeRow(selectedRow); // xóa trên giao diện
        }
        
    }
});
        editItem.addActionListener(e -> {
        
        int selectedRow = Admin_QLUSER_TABLE.getSelectedRow();
        if (selectedRow >= 0) {
        
        
        int id = (int) defaultTableModelQLUSER.getValueAt(selectedRow, 0);
        
        new EditUser(id).setVisible(true);
    }
    
});



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_QLUSER_TABLE = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Admin_QLUSER_Label = new javax.swing.JLabel();
        admin_Add_User_BTN = new javax.swing.JButton();
        Admin_QLUSER_Refresh_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý User");
        setMinimumSize(new java.awt.Dimension(600, 600));

        Admin_QLUSER_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Admin_QLUSER_TABLE.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Admin_QLUSER_TABLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Admin_QLUSER_TABLE);

        Admin_QLUSER_Label.setBackground(new java.awt.Color(255, 255, 255));
        Admin_QLUSER_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_QLUSER_Label.setText("Quản Lý Users");
        Admin_QLUSER_Label.setAlignmentX(0.5F);

        admin_Add_User_BTN.setText("Thêm user");
        admin_Add_User_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_Add_User_BTNActionPerformed(evt);
            }
        });

        Admin_QLUSER_Refresh_BTN.setText("Refresh");
        Admin_QLUSER_Refresh_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLUSER_Refresh_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_Add_User_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_QLUSER_Refresh_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(793, 793, 793)
                .addComponent(Admin_QLUSER_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Admin_QLUSER_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin_Add_User_BTN)
                    .addComponent(Admin_QLUSER_Refresh_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(832, 832, 832)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 313, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_QLUSER_Refresh_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLUSER_Refresh_BTNActionPerformed
        // TODO add your handling code here:
        defaultTableModelQLUSER.setRowCount(0);
        InsertData(userService.getAllUser());
    }//GEN-LAST:event_Admin_QLUSER_Refresh_BTNActionPerformed

    private void admin_Add_User_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_Add_User_BTNActionPerformed
        // TODO add your handling code here:
        new AddUser().setVisible(true);
        
    }//GEN-LAST:event_admin_Add_User_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_QLUSER_Label;
    private javax.swing.JButton Admin_QLUSER_Refresh_BTN;
    private javax.swing.JTable Admin_QLUSER_TABLE;
    private javax.swing.JButton admin_Add_User_BTN;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
