/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.service.Admin.QLPRODUCT;


import com.mycompany.model.Category;
import com.mycompany.service.Admin.ProductService;
import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Product;
import com.mycompany.model.Category;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author VITHANH
 */
public class EditProduct extends javax.swing.JFrame {
    private int saveID;
            
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProduct.class.getName());

    /**
     * Creates new form EditProduct
     */
    public EditProduct(int id) {
    initComponents();
    this.saveID = id;
    
    ProductService proSer = new ProductService();
    Product pro = proSer.getProductById(id);
    
    CategoryService cateSer = new CategoryService();
    Category cate = cateSer.getCategoryByID(pro.getCateid());
    String cateName = cate.getName();
    
    Admin_Edit_Product_ID_Textfield.setText(Integer.toString(pro.getId()));

    // ✅ Đúng: Lấy danh sách Category
    List<Category> categoryList = cateSer.getAllCategory();
    Admin_Edit_Product_Category_Combobox.removeAllItems(); // Clear combobox trước khi add
    for (Category c : categoryList) {
        Admin_Edit_Product_Category_Combobox.addItem(c.getName()); // ✅ Add tên category
    }

    Admin_Edit_Product_Category_Combobox.setSelectedItem(cateName); // ✅ Set tên tương ứng

    Admin_Edit_Product_Name_Textfield.setText(pro.getName());
    Admin_Edit_Product_Desc_TextArea.setText(pro.getDescription());
    Admin_Edit_Product_Price_Textfield.setText(Double.toString(pro.getPrice()));
    Admin_Edit_Product_ImagePath_Textfield.setText(pro.getImagepath());
}

    public EditProduct() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Admin_Edit_Product_Header_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Admin_Edit_Product_Name_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ImagePath_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ID_Label = new javax.swing.JLabel();
        Admin_Edit_Product_Category_Label = new javax.swing.JLabel();
        Admin_Edit_Product_Name_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_Price_Label = new javax.swing.JLabel();
        Admin_Edit_Product_ID_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_ImagePath_Textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_Edit_Product_Desc_TextArea = new javax.swing.JTextArea();
        Admin_Edit_Product_Price_Textfield = new javax.swing.JTextField();
        Admin_Edit_Product_Category_Combobox = new javax.swing.JComboBox<>();
        Admin_Edit_Product_Description_Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Admin_Edit_Product_HuyBTN = new javax.swing.JButton();
        Admin_Edit_Product_SaveBTN = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Admin_Edit_Product_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_Edit_Product_Header_Label.setText("Chỉnh sửa Product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Product_Header_Label)
                .addGap(296, 296, 296))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_Product_Header_Label)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Admin_Edit_Product_Name_Label.setText("Name: ");

        Admin_Edit_Product_ImagePath_Label.setText("Imagepath:");

        Admin_Edit_Product_ID_Label.setText("ID:");

        Admin_Edit_Product_Category_Label.setText("Category: ");

        Admin_Edit_Product_Price_Label.setText("Price: ");

        Admin_Edit_Product_ID_Textfield.setEditable(false);

        Admin_Edit_Product_Desc_TextArea.setColumns(20);
        Admin_Edit_Product_Desc_TextArea.setRows(5);
        jScrollPane1.setViewportView(Admin_Edit_Product_Desc_TextArea);

        Admin_Edit_Product_Description_Label.setText("Description:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Product_Name_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Admin_Edit_Product_Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Product_ID_Label)
                        .addGap(42, 42, 42)
                        .addComponent(Admin_Edit_Product_ID_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin_Edit_Product_Category_Label)
                    .addComponent(Admin_Edit_Product_Price_Label))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_Product_Price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Edit_Product_Category_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_Edit_Product_ImagePath_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Product_Description_Label)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Admin_Edit_Product_ImagePath_Label)
                        .addGap(230, 230, 230))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_Product_ID_Label)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Admin_Edit_Product_ID_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Admin_Edit_Product_Category_Label)
                        .addComponent(Admin_Edit_Product_Category_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Product_Name_Label)
                    .addComponent(Admin_Edit_Product_Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Edit_Product_Description_Label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admin_Edit_Product_Price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Admin_Edit_Product_Price_Label))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Admin_Edit_Product_ImagePath_Label)
                            .addComponent(Admin_Edit_Product_ImagePath_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        Admin_Edit_Product_HuyBTN.setText("Hủy");
        Admin_Edit_Product_HuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Product_HuyBTNActionPerformed(evt);
            }
        });

        Admin_Edit_Product_SaveBTN.setText("Lưu");
        Admin_Edit_Product_SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Edit_Product_SaveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Edit_Product_SaveBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admin_Edit_Product_HuyBTN)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Edit_Product_HuyBTN)
                    .addComponent(Admin_Edit_Product_SaveBTN))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Edit_Product_HuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Product_HuyBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_Edit_Product_HuyBTNActionPerformed

    private void Admin_Edit_Product_SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Edit_Product_SaveBTNActionPerformed
        // TODO add your handling code here:
        String name = Admin_Edit_Product_Name_Textfield.getText();
    String description = Admin_Edit_Product_Desc_TextArea.getText();
    String priceText = Admin_Edit_Product_Price_Textfield.getText();
    String imagePath = Admin_Edit_Product_ImagePath_Textfield.getText();
    String categoryName = (String) Admin_Edit_Product_Category_Combobox.getSelectedItem();

    // Ép kiểu và kiểm tra dữ liệu đầu vào (bạn có thể bổ sung validate nếu muốn)
    double price = 0.0;
    try {
        price = Double.parseDouble(priceText);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Giá không hợp lệ!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lấy ID Category từ tên Category
    CategoryService cateSer = new CategoryService();
    Category category = cateSer.getCategoryByName(categoryName); // 🔸 Giả sử bạn có hàm này
    if (category == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy danh mục!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tạo đối tượng Product
    Product product = new Product();
    product.setId(saveID); // saveID là ID của product đang sửa
    product.setName(name);
    product.setDescription(description);
    product.setPrice(price);
    product.setImagepath(imagePath);
    product.setCateid(category.getId());

    // Cập nhật DB
    ProductService proSer = new ProductService();
    proSer.updateProduct(product);

    // Đóng form sau khi lưu xong
    this.dispose();
    }//GEN-LAST:event_Admin_Edit_Product_SaveBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Admin_Edit_Product_Category_Combobox;
    private javax.swing.JLabel Admin_Edit_Product_Category_Label;
    private javax.swing.JTextArea Admin_Edit_Product_Desc_TextArea;
    private javax.swing.JLabel Admin_Edit_Product_Description_Label;
    private javax.swing.JLabel Admin_Edit_Product_Header_Label;
    private javax.swing.JButton Admin_Edit_Product_HuyBTN;
    private javax.swing.JLabel Admin_Edit_Product_ID_Label;
    private javax.swing.JTextField Admin_Edit_Product_ID_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_ImagePath_Label;
    private javax.swing.JTextField Admin_Edit_Product_ImagePath_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_Name_Label;
    private javax.swing.JTextField Admin_Edit_Product_Name_Textfield;
    private javax.swing.JLabel Admin_Edit_Product_Price_Label;
    private javax.swing.JTextField Admin_Edit_Product_Price_Textfield;
    private javax.swing.JButton Admin_Edit_Product_SaveBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
