/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.service.Admin.QLPRODUCT;

import com.mycompany.service.Admin.ProductService;
import com.mycompany.service.Admin.CategoryService;
import com.mycompany.model.Product;
import com.mycompany.model.Category;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author VITHANH
 */
public class QuanLyProduct extends javax.swing.JFrame {
    ProductService productService;
    DefaultTableModel defaultTableModel;
    CategoryService categoryService;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyProduct.class.getName());

    /**
     * Creates new form QuanLyProduct
     */
    public void insertData(List<Product> productList){
        for(Product pro : productList){
            categoryService = new CategoryService();
            Category cate = categoryService.getCategoryByID(pro.getId());
            String cateName = cate.getName();
            defaultTableModel.addRow(new Object[]{pro.getId(), cateName,pro.getName(), pro.getDescription(), pro.getPrice(), pro.getImagepath()});
        }
    }
    public QuanLyProduct() {
        initComponents();
        productService = new ProductService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        };
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("CATEGORY NAME");
        defaultTableModel.addColumn("NAME");
        defaultTableModel.addColumn("DESCRIPTION");
        defaultTableModel.addColumn("PRICE");
        defaultTableModel.addColumn("IMAGEPATH");
        
        Admin_QLPRODUCT_TABLE.setModel(defaultTableModel);
        
        insertData(productService.getAllProduct());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admin_QLPRODUCT_TABLE = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Admin_QLPRODUCT_Header_Label = new javax.swing.JLabel();
        Admin_QLPRODUCT_Refresh_ProductBTN = new javax.swing.JButton();
        Admin_QLPRODUCT_Add_ProductBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin_QLPRODUCT_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Admin_QLPRODUCT_TABLE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        Admin_QLPRODUCT_Header_Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Admin_QLPRODUCT_Header_Label.setText("Quản Lý Product");

        Admin_QLPRODUCT_Refresh_ProductBTN.setText("Refresh");

        Admin_QLPRODUCT_Add_ProductBTN.setText("Thêm");
        Admin_QLPRODUCT_Add_ProductBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_QLPRODUCT_Add_ProductBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_QLPRODUCT_Add_ProductBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(Admin_QLPRODUCT_Header_Label)
                .addGap(174, 174, 174)
                .addComponent(Admin_QLPRODUCT_Refresh_ProductBTN)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_QLPRODUCT_Refresh_ProductBTN)
                    .addComponent(Admin_QLPRODUCT_Header_Label)
                    .addComponent(Admin_QLPRODUCT_Add_ProductBTN))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_QLPRODUCT_Add_ProductBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_QLPRODUCT_Add_ProductBTNActionPerformed
        // TODO add your handling code here:
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_Admin_QLPRODUCT_Add_ProductBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_QLPRODUCT_Add_ProductBTN;
    private javax.swing.JLabel Admin_QLPRODUCT_Header_Label;
    private javax.swing.JButton Admin_QLPRODUCT_Refresh_ProductBTN;
    private javax.swing.JTable Admin_QLPRODUCT_TABLE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
